name: Build and Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make build
      working-directory: ${{github.workspace}}
    - env:
        SUPER_SECRET: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      run: echo "$SUPER_SECRET" | docker login -u _json_key --password-stdin https://us-east4-docker.pkg.dev
    - run: docker push us-east4-docker.pkg.dev/atyeti-backstage/backstage/app:latest